services:
  fail2ban:
    image: "crazymax/fail2ban:${FAIL2BAN_VERSION:-1.1.0}"
    environment:
      TZ: "Europe/Berlin"
      F2BD_ADDRESS: ":3000"
      F2BD_LOG_LEVEL: "debug"
      F2BD_SKIP_VERSION_CHECK: "true"
      F2BD_TRUST_PROXY_HEADERS: "true"
      F2BD_REFRESH_SECONDS: 15
    ports:
      - "3000:3000"
    volumes:
      - "../bin:/app"
      - "./data/script:/script"
      - "./data/jail.d:/data/jail.d"
      - "./data/filter.d:/data/filter.d"
      - "./data/log:/var/log/test"
      - "/etc/localtime:/etc/localtime:ro"


